### ISSUE TITLE
[Arduino] 十字ボタンを斜め入力した後に、片方のボタンを離すと両方のボタンを離したことになる。

### ISSUE THREAD

**Issue by ghost** [noov-smash/PhantomHand#2]
添付の動画が例となります。
右上(↗️)　→　上（↑）とした際に、上(↑)の入力がPCからArduinoまで送信されますが、Arduino側にはNEUTRALとして送信されます。
https://github.com/user-attachments/assets/fac1b983-fe05-4ef7-9db1-28132aa18bd4

↖️　↙️　↘️も同様となります。

` SwitchControlLibrary().releaseHatButton()`の処理が引数に関係なく、十字ボタンの入力 NEUTRALとして処理されるためです。

上下左右各方向のON・OFFをbool変数に格納し、変数の内容から入力内容を判断してSwitchに送信するように変更することでこの事象が解決できます。

void setControllerStates(){
  //data[0] 0～11までの処理
  else if (data[0] == 12) {
    if(data[1] == 1) UP_PRESSED = true;
    else UP_PRESSED = false;
  }
  else if (data[0] == 13) {
    if(data[1] == 1) DOWN_PRESSED = true;
    else DOWN_PRESSED = false;
  }
  else if (data[0] == 14) {
    if(data[1] == 1) LEFT_PRESSED = true;
    else LEFT_PRESSED = false;
  }
  else if (data[0] == 15) {
    if(data[1] == 1) RIGHT_PRESSED = true;
    else RIGHT_PRESSED = false;
  }
   
  //data[0] = 16～21までの処理
  
  //Hat Input Setting
  if(UP_PRESSED && !DOWN_PRESSED && !LEFT_PRESSED && !RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::UP);
  else if(UP_PRESSED && !DOWN_PRESSED && !LEFT_PRESSED && RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::UP_RIGHT);
  else if(!UP_PRESSED && !DOWN_PRESSED && !LEFT_PRESSED && RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::RIGHT);
  else if(!UP_PRESSED && DOWN_PRESSED && !LEFT_PRESSED && RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::DOWN_RIGHT);
  else if(!UP_PRESSED && DOWN_PRESSED && !LEFT_PRESSED && !RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::DOWN);
  else if(!UP_PRESSED && DOWN_PRESSED && LEFT_PRESSED && !RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::DOWN_LEFT);
  else if(!UP_PRESSED && !DOWN_PRESSED && LEFT_PRESSED && !RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::LEFT);
  else if(UP_PRESSED && !DOWN_PRESSED && LEFT_PRESSED && !RIGHT_PRESSED) SwitchControlLibrary().pressHatButton(Hat::UP_LEFT);
  else SwitchControlLibrary().releaseHatButton(Hat::NEUTRAL);
}

**Comment by noov-smash** [comment]
[7165696953556ae3d719cbf1d1688f23d38ad186](https://github.com/noov-smash/PhantomHand-Arduino/commit/7165696953556ae3d719cbf1d1688f23d38ad186) にて対応しました！
